---
- name: Assert next partition exists
  assert:
    that:
      - next_partition is defined
      - next_partition | length > 0
    fail_msg: "No partition found after {{ root_partition }} on disk {{ root_disk }}"

- name: Assert part_luks_passphrase is defined, can be decrypted and strong enough
  assert:
    that:
      - part_luks_passphrase is defined
      - part_luks_passphrase is not search("^\\$ANSIBLE_VAULT")
      - part_luks_passphrase | length >= 8
    fail_msg: "Variable part_luks_passphrase must be set and at least 8 characters."

- name: Assert mountpoint is not root
  assert:
    that:
      - part_mount_point != '/'
    fail_msg: "Mountpoint cannot be /"


- name: Assert keyfile path is safe if part_use_keyfile is enabled
  assert:
    that:
      - part_luks_keyfile is defined
      - part_luks_keyfile is match('^/root/')
    fail_msg: "Keyfile must be inside /root/ when part_use_keyfile is enabled."
  when: part_use_keyfile
